data:
  raw_path: data/raw_dataset.csv
  processed_path: data/dataset_processed.csv
  train_path: data/train.csv
  val_path: data/val.csv
  test_path: data/test.csv
  val_ratio: 0.1
  test_ratio: 0.1
  max_rows: 1000

tokenization:
  lowercase: true
  remove_urls: true
  remove_mentions: true
  remove_emojis: false
  max_vocab_size: 30000
  sequence_length: 64

model:
  type: lstm
  vocab_size: 30000
  embedding_dim: 256
  hidden_dim: 128
  num_layers: 2
  dropout: 0.1

training:
  batch_size: 256
  num_epochs: 5
  learning_rate: 0.001
  seed: 42
  device: cuda

generation:
  max_new_tokens: 20
  strategy: greedy  # options: greedy, top_k, nucleus
  top_k: 50
  top_p: 0.95

transformer:
  model_name: distilgpt2
  max_length: 20
  do_sample: true
  top_k: 50
  top_p: 0.95

output:
  model_dir: models/
  checkpoints_dir: models/checkpoints/

